name: health_check_ext
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  go_router: ^17.1.0
  flutter_svg: ^2.0.17
  loading_indicator: ^3.1.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.9.0
flutter:
  uses-material-design: true

  assets:
    - assets/wifi.svg
    - assets/check-square-svgrepo.svg
    - assets/clock_speed.svg
    - assets/devices-svgrepo-com.svg
    - assets/doc-text-svgrepo-com.svg
    - assets/help-circle-svgrepo-.svg
    - assets/loading-16-svgrepo-c.svg
    - assets/robot.svg
    - assets/wifi_off.svg
    - assets/logos/

    
