name: health_check_ext
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  flutter_svg: ^2.0.17
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/wifi.svg
    - assets/check-square-svgrepo.svg
    - assets/clock_speed.svg
    - assets/devices-svgrepo-com.svg
    - assets/doc-text-svgrepo-com.svg
    - assets/help-circle-svgrepo-.svg
    - assets/loading-16-svgrepo-c.svg
    - assets/robot.svg
    - assets/wifi_off.svg
    - assets/logos/logo_riot.png
    - assets/logos/logo_valve.png
    - assets/logos/logo_epic_games.png
    - assets/logos/logo_activision.png
    - assets/logos/logo_ea.png
    - assets/

    
